require('capybara/rspec')
require('./app')
Capybara.app = Sinatra::Application
set(:show_exceptions, false)

describe('the word definition path', {:type => :feature}) do
  it('allows a user to add a word, and then add multiple definitions for that word') do
    visit('/')
    click_link('Add a word')
    expect(page).to have_content('Add a word')
    fill_in('word', :with => 'mountain')
    click_button('Add Word')
    expect(page).to have_content('Successfully added!')
    click_link('See the list of words')
    expect(page).to have_content('Words')
    click_link('mountain')
    expect(page).to have_content('Definitions for mountain')
    click_link('Add a new definition')
    expect(page).to have_content('Add a definition to mountain')
    fill_in('part_of_speech', :with => 'noun')
    fill_in('meaning', :with => 'much bigger than a hill')
    click_button('Add Definition')
    expect(page).to have_content('Successfully added!')
    click_link('See the list of words')
    expect(page).to have_content('Words')
    click_link('mountain')
    expect(page).to have_content('much bigger than a hill')
    click_link('Add a new definition')
    expect(page).to have_content('Add a definition to mountain')
    fill_in('part_of_speech', :with => 'adjective')
    fill_in('meaning', :with => 'as in from the mountains')
    click_button('Add Definition')
    expect(page).to have_content('Successfully added!')
    click_link('See the list of words')
    expect(page).to have_content('Words')
    click_link('mountain')
    expect(page).to have_content('as in from the mountains')
  end
end
